services:
  - type: web
    name: shoestore-api
    env: node
    plan: free
    branch: main
    rootDir: apps/api
    autoDeploy: true
    healthCheckPath: /health

    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm prisma generate
      pnpm build

    startCommand: node dist/index.js

    postdeployCommand: pnpm prisma migrate deploy

    envVars:
      - key: NODE_ENV
        value: production

      # CORS cho web local và Vercel previews/prod
      - key: CORS_ALLOWLIST
        value: http://localhost:3000,https://*.vercel.app

      # Secrets tự sinh trên Render
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true

      # Kết nối DB lấy từ database bên dưới
      - key: DATABASE_URL
        fromDatabase:
          name: shoestore-db
          property: connectionString

      # Điền các key Stripe trong Render Dashboard (không thể generate)
      - key: STRIPE_SECRET_KEY
        value: ""
      - key: STRIPE_WEBHOOK_SECRET
        value: ""

databases:
  - name: shoestore-db
    plan: free
