databases:
  - name: shoestore-db
    plan: free
    postgresMajorVersion: 15

services:
  - type: web
    name: shoestore-api
    env: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: |
      pnpm i --frozen-lockfile
      pnpm -C packages/shared build
      pnpm -C apps/api prisma:generate
      pnpm -C apps/api build
    startCommand: |
      node apps/api/dist/src/index.js
      pnpm -C apps/api prisma:migrate:deploy
      pnpm -C apps/api prisma:seed
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: shoestore-db
          property: connectionString
      - key: JWT_SECRET
        value: "set-in-dashboard"
      - key: JWT_REFRESH_SECRET
        value: "set-in-dashboard"
      - key: COOKIE_SECRET
        value: "set-in-dashboard"
      - key: CSRF_SECRET
        value: "set-in-dashboard"
      - key: STRIPE_SECRET_KEY
        value: "set-in-dashboard"
      - key: STRIPE_WEBHOOK_SECRET
        value: "set-in-dashboard"
      - key: IMAGE_DOMAIN_ALLOWLIST
        value: "images.unsplash.com,cdn.example.com"
      - key: CORS_ALLOWLIST
        value: "http://localhost:3000,https://*.vercel.app"
